### ISSUE TITLE
Docker IIS WindowsServerCore Image - Not able to read environment variable

### ISSUE THREAD

**Issue by nareshkhatri81** [Microsoft/iis-docker#75] opened 2018-01-17 05:01 UTC
Hi Team,

We are setting environment variable like below in init.bat file. 

When i do docker exec command to see inside containers i can see those environmental variable set but when IIS process(Asp.net) try to read, it doesn't find those. we are deploying containers via Service Fabric.
Below is sample docker file 

FROM microsoft/iis:windowsservercore-ltsc2016
SHELL ["powershell"]

RUN Install-WindowsFeature NET-Framework-45-ASPNET ; \
    Install-WindowsFeature Web-Asp-Net45

CMD init.bat

COPY webContain webContain

RUN icacls "C:\webContain" /grant IIS_IUSRS:F /T

RUN Remove-WebSite -Name 'Default Web Site'

RUN New-Website -Name 'WebContainer' -Port 84\
    -PhysicalPath 'c:\webContain' -ApplicationPool '.NET v4.5'
EXPOSE 84

CMD Write-Host IIS Started... ; \
    while ($true) { Start-Sleep -Seconds 3600 }

Below are contents of init.cmd where we set environmental variables

setx /M PATH %PATH%;C:\sffabricbin 
set PATH=%PATH%;C:\sffabricbin 

Thanks,
Naresh Khatri

**Comment by bariscaglar** [comment] 2018-01-17 19:24
@mcy94w can you take a look?

**Comment by artisticcheese** [comment] 2018-01-25 02:29
Make sure you are not running into problem below
https://github.com/moby/moby/issues/30192

**Comment by nareshkhatri81** [comment] 2018-01-25 12:31
@artisticcheese 
Env variable are set using setx command and set command inside docker image.

**Comment by artisticcheese** [comment] 2018-01-25 12:40
Are you sure setx is setting machine level environment variable? Also please use .NET or powershell. I don't understand how you can possibly work with docker etc and still go back to batch commands.

**Comment by nareshkhatri81** [comment] 2018-01-25 13:31
@artisticcheese 
Thing here is we are dependent upon Microsoft two exes
C:\SFFabricBin\vc14_redist.x64.exe -quiet
C:\SFFabricBin\vcredist_x64.exe -quiet

 which runs and setup number of environment variables which i can see when i do docker exec command but IIS w3wp process is not able to get to those variables.
https://github.com/Azure/service-fabric-scripts-and-templates/blob/master/scripts/CodePackageToDockerPackage/CreateDockerPackage.ps1

Thanks,
Naresh Khatri

**Comment by artisticcheese** [comment] 2018-01-25 13:38
I beleive `setx` sets user or session level process variables, so they will not be visible from our sessions. If you want to create machine level variable yourself you can use .NET classes to do that.

**Comment by mcy94w** [comment] 2018-02-05 19:21
@nareshkhatri81 :

ServiceMonitor.exe only setup Env Var once when the container start. Can you confirm when the serviceMonitor.exe start, those Env Var already exist?

**Comment by bariscaglar** [comment] 2018-05-08 17:25
@mcy94w, @nareshkhatri81 can we close this?

**Comment by nareshkhatri81** [comment] 2018-05-08 17:29
I need to perform few more test this week.
Let me update by end of this week.

**Comment by shirhatti** [comment] 2018-06-19 00:06
Hi. We're closing this issue as no response or updates have been provided   in a timely manner and we have been unable to reproduce it. If you have more   details and are encountering this issue please add a new reply and re-open   the issue.

**Closed** 2018-06-19 00:07 UTC
Labels: investigating
