### ISSUE TITLE
Connect to Dockerized IIS remotely

### ISSUE THREAD

**Issue by hmdhasani** [Microsoft/iis-docker#15] opened 2016-12-03 07:31 UTC
Is there any way to connect to the inside container IIS from an IIS Manager so I could have a GUI Access to that IIS?

**Comment by hmdhasani** [comment] 2016-12-03 07:41
I followed this:
https://technet.microsoft.com/en-us/library/dn198619.aspx
and it seems that my IIS Manager could see the IIS but I got Authentication error. It seems the user must be ContainerManager but I don't know the password

**Comment by shirhatti** [comment] 2016-12-07 00:09
Closing as dupe of #16

**Closed by shirhatti** 2016-12-07 00:09 UTC
