### ISSUE TITLE
Latest windowsservercore-10.0.14393.693 suspiciously large

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/iis-docker#21] opened 2017-01-15 09:20 UTC
I noticed for windowsservercore-10.0.14393.693 a 4+ GB layer is downloaded. This does not match with previous versions, which were in the hundreds of MB as far as I recall.

I lack the Docker expertise to diagnose but it feels like the Windows base layer was also re-downloaded for no reason. Possibly caused by https://github.com/docker/docker/issues/30080 ?

**Comment by shirhatti** [comment] 2017-01-17 19:47
@sandersaares Thanks for catching that, and yes it was caused by the linked bug.
We're about to purge our offending images and re-upload images to DockerHub.

**Comment by shirhatti** [comment] 2017-01-21 01:09
This was fixed on 1/18.
New images are available on DockerHub.

**Closed by shirhatti** 2017-01-21 01:09 UTC
