### ISSUE TITLE
How do you use UI tools with Microsoft containers?

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/iis-docker#18] opened 2017-01-05 00:52 UTC
Hello,

I figured out how to use IIS manager to remotely manage IIS container by creating local username/password, adding it to Adminstrators group, installing IIS management service and configure it to allow remote connections. I can not make work any sort of remote administration tools like EventViewer for example. I suspect it's because Microsoft disabled "srvnet" service and all relevant dependencies. I understand removing may be terminal services but completely crippling all remote administration is pure craziness. This is absolutely required for image development and troubleshooting. I understand majority can be done via remoting but Microsoft raised bar too high for entrance to this space for all developers to want to come onboad. It's alrady difficult enough to persuade them to use containers but now you have to require them to learn powershell to pull eventlogs?

**Comment by shirhatti** [comment] 2017-01-05 18:27
@patricklang What's the best guidance to give to folks trying retrieve EventLogs?

**Comment by PatrickLang** [comment] 2017-01-05 18:36
PowerShell or wevtutil.exe are the only options right now. I would also consider tools for central logging collection such as OMS, Splunk, or similar so that you can gather all logs in one place. This is doubly important if you're going to be doing blue/green deployments where you replace the running containers on a regular basis rather than keeping them running for a long time.

Please share your UI feedback on UserVoice - we're collecting info on how people would use UI there:
https://windowsserver.uservoice.com/forums/304624-containers 

Thanks!

**Comment by artisticcheese** [comment] 2017-01-08 15:03
Anybody running into this issue please upvote this suggestion (https://windowsserver.uservoice.com/forums/304624-containers/suggestions/17660338-enable-server-service-and-mmc-ui-management-capa)
The more I work with containers in current incarnation then more I question wether I will be able to sell idea of using containers for either new or old applications to developers because it's supposed to be a heaven for developer but current limitations it's really making a hell for them to debug.

**Comment by rs38** [comment] 2017-01-09 10:06
I think it contradicts with the container philosophy to have UIs attached to it in order to manage them. The same is true for logging: as container are only a temporary entitiy it would make more sense that they PUSH their logs to a central data sink instead being queried?!

**Comment by artisticcheese** [comment] 2017-01-09 12:49
How does it contract with methodology? Containers still don't have UI, this UI is used externally to manage running containers for debugging/maintenance purposes. I know very few companies which using Server Core exclusively for production workloads and even those still rely on external tools for day to day administration. Completely removing essential tool like event log was mistake on Microsoft's part. It's already difficult enough to deal with containers in current encarnation but this will completely turn off people wanting to adopt it. Even Nano server allows remote UI management to ease adoption.
We can talk about centralizing logging etc when we come to that point but right now this stop evening basic development tasks from progressing, how you are supposed to tell developer which has used Visual Studio, full blown Windows UI etc to start working with OS which can not be managed remotely at all?

**Comment by rs38** [comment] 2017-01-09 13:08
I disagree! I think you will take the wrong direction if you rely on exposing API for GUIs.
the way to deal with containers is not the same as with some normal headless windows servers.
Containers should be quite stateless and every step you take by GUI tools may help in the first view, but you cannot automate things as it should be.
What kind of sense it would make to expose a mgmt API for a container that is part of a swarm where a particular container can die and restartet with other network endpoints? 

**I do agree** that it is very hard to become familiar with MS containers as there is quite a big break in the things windows did it decades long, but there is no need to get virtuallay everthing running in containers only because they are available.

**Comment by artisticcheese** [comment] 2017-01-09 13:11
I'm not asking to enable UI and remove command line management tools but instead to enable UI and still leave command management tools. There is a reason why Windows became so popular and it's due to UI and being user friendly. You can still have UI and fully automatable solution, they do not contract to each other at all (see Nano server for example).

**Comment by rs38** [comment] 2017-01-10 12:01
so feel free to configure your container images as you need it, but I think it is the right way NOT to enable them as default.

**Comment by artisticcheese** [comment] 2017-01-10 12:30
It's impossible to enabled it. Microsoft on purpose castrated image for some reason.

**Comment by rs38** [comment] 2017-01-10 13:03
just tested a servercore image and srvnet runs fine...

**Comment by artisticcheese** [comment] 2017-01-10 13:09
Wondering if it's only microsoft/iis which is castrated. It does not start on microsoft/iis at all. Checking it.

**Comment by artisticcheese** [comment] 2017-01-10 13:27
srvany does not work on servercore image either for me? Are you sure it's running fine for you?

**Comment by rs38** [comment] 2017-01-10 14:05
yes, all dependend services of lanmanserver are running fine. but lanmanserver stops with an error 
"the server service terminated with the following error: %%2"

probably you need to set the role/feature for files services before (which I did not)

**Comment by artisticcheese** [comment] 2017-01-10 14:07
This is on microsoft/windowservercore image? I downloaded fresh one from docker hub and can not start srvnet service.

**Comment by rs38** [comment] 2017-01-10 14:12
my image was pulled/updated 1-2 months ago.

please check `get-windowsfeature fs-fileserver`

**Comment by artisticcheese** [comment] 2017-01-10 14:16
Nope did not work neither on iis or servercoreimage I just pulled. Here is image I used (latest available)

`microsoft/windowsservercore   latest              7baaa272ad7d        4 weeks ago         9.42 GB`

**Comment by rs38** [comment] 2017-01-10 14:23
I tested with core image 10.0.14393.447

**Comment by artisticcheese** [comment] 2017-01-10 14:50
Installed the same image as yours and still can not start that service (srvnet). This seems to be difference between Hyper-V container and process container. When I run this on Hyper-V container on Windows 10 it fails to start but works fine on Windows 2016 in process container.

**Comment by rs38** [comment] 2017-01-10 15:07
indeed I tested as Win 2016 server container

**Comment by artisticcheese** [comment] 2017-01-10 15:08
Well even with srvnet service running and File-Services installed it's still not working. Server service can not be started.

**Comment by rs38** [comment] 2017-01-10 16:54
I think this will be a bug it does not sound like exactly intended. You should place it in one of the support groups or may be digging deeper by yourself und debug the root cause...

**Comment by shirhatti** [comment] 2017-08-16 21:27
Closing this issue, as it's not actionable from IIS

**Closed by shirhatti** 2017-08-16 21:27 UTC

**Comment by halr9000** [comment] 2017-11-30 19:51
For posterity, just found this issue after working w/MS and a customer who had a related question. The recommendation we came up with was to use the Windows Event Log Forwarding feature from the containers, to another system (probably the host) for event logs, and shared volumes for filesystem logs. From there, you can use data aggregation tools such as Splunk on that system, or your usual GUI tools.
